/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start_vane_web3: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: any) => any;
export const __wbg_publicinterfaceworkerjs_free: (a: number, b: number) => void;
export const publicinterfaceworkerjs_addAccount: (a: number, b: number, c: number, d: any) => any;
export const publicinterfaceworkerjs_clearCache: (a: number) => [number, number];
export const publicinterfaceworkerjs_clearFinalizedFromCache: (a: number) => [number, number];
export const publicinterfaceworkerjs_clearRevertedFromCache: (a: number) => [number, number];
export const publicinterfaceworkerjs_deleteTxInCache: (a: number, b: any) => [number, number];
export const publicinterfaceworkerjs_exportStorage: (a: number) => any;
export const publicinterfaceworkerjs_fetchPendingTxUpdates: (a: number, b: number, c: number) => any;
export const publicinterfaceworkerjs_fetchTxSessionLogs: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const publicinterfaceworkerjs_initiateTransaction: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: bigint, i: bigint, j: any, k: number, l: number, m: any, n: any, o: bigint, p: bigint) => any;
export const publicinterfaceworkerjs_receiverConfirm: (a: number, b: number, c: number, d: any) => any;
export const publicinterfaceworkerjs_revertTransaction: (a: number, b: number, c: number, d: any, e: number, f: number) => any;
export const publicinterfaceworkerjs_senderConfirm: (a: number, b: number, c: number, d: any) => any;
export const publicinterfaceworkerjs_unsubscribeWatchP2pNotifications: (a: number) => [number, number];
export const publicinterfaceworkerjs_unsubscribeWatchTxUpdates: (a: number) => [number, number];
export const publicinterfaceworkerjs_verifyTxCallPayload: (a: number, b: any) => any;
export const publicinterfaceworkerjs_watchP2pNotifications: (a: number, b: any) => any;
export const publicinterfaceworkerjs_watchTxUpdates: (a: number, b: any) => any;
export const __wbg_requestarguments_free: (a: number, b: number) => void;
export const requestarguments_method: (a: number) => [number, number];
export const requestarguments_params: (a: number) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hbb9c5e38079b62e8: (a: number, b: number) => void;
export const closure548_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5e0f7080e7fd3769: (a: number, b: number) => void;
export const closure763_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h76454f8444f73094: (a: number, b: number) => void;
export const closure845_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
